### ISSUE TITLE
[FEATURE REQUEST] Graph visualizer

### ISSUE THREAD

**Issue by pietroferrara** [UniVE-SSV/lisa#197]
**Description**
Import the graph visualizer deveoped by Alessio into the main trunk of LiSA

**Motivation**
It allows to easily navigate and inspect the results.

**Suggested implementation**

https://github.com/Alessio-Campa/lisa/commits/master

**Comment by lucaneg** [comment]
Related to #128. Most of the work done in the fork will be rewritten.
