### ISSUE TITLE
[BUG] Loss of previously gathered information when calling constructors

### ISSUE THREAD

**Issue by VincenzoArceri** [UniVE-SSV/lisa#31]
**Description**
A call to a constructor, using the Intraprocedural call graph abstraction, returns the top abstract state, causing the loss of any previously gathered analysis information. Informally speaking, when a constructor is called, it is as the analysis restarted from the point the constructor is called.

**Reproducibility information**
In branch `program-structure` (commit: 680e53a92a184b9cc9936686c2d0e518d4104a22). Let's consider the following IMP program
```
class example {
	f(e) {
		def obj = new example();
	}
}
```
and let's suppose to analyze it using the default abstractions for the CallGraph (`IntraproceduralCallGraph`) and HeapDomain (`MonohiliticHeap`), and `Sign` for the ValueDomain. The result of the analysis is reported in the following, by means of the corresponding dumped dot file.
<img width="237" alt="Schermata 2021-01-25 alle 10 39 02" src="https://user-images.githubusercontent.com/3504323/105688158-8c618100-5ef9-11eb-9ff5-79310181528c.png">
Note that, the abstract value regarding the parameter `e` (namely `TOP`, the top of the Sign domain) is lost. 
The expected result is the same dot file, except that in the first node the value analysis also contains the information about the parameter `e`, i.e., contains the entry `vid$e: TOP`.

**Comment by lucaneg** [comment]
Unfortunately that is the consequence of being sound with an interprocedural analysis: whenever you find a cfg call, the whole abstract state has to be set to top since you are not really taking into account what happens inside that cfg. This will be different with different callgraph implementations.
